export const data = [
  {
    name: "Box of Orginal Jars (250ml x 5)",
    price: 180,
    images: ["/public/nhs.png"],
    slug: "classic-tiramisu",
    weight: "250ml X 5",
    type: "box",
    description:
      "Delicious classic Tiramisu with rich cream and coffee flavor.",
    reviews: 4.5,
  },
  {
    name: "Box of Pistachio Jars (500ml x 5)",
    price: 180,
    images: ["/public/nhs.png"],
    slug: "pistachio-tiramisu",
    weight: "150ml X 9",
    type: "box",
    description: "Nutty Pistachio flavor Tiramisu with soft texture.",
    reviews: 4.2,
  },
  {
    name: "Classic Tiramisu",
    price: 180,
    images: ["/public/nhs.png"],
    slug: "classic-tiramisu",
    weight: "500ml",
    type: "large",
    description:
      "Delicious classic Tiramisu with rich cream and coffee flavor.",
    reviews: 4.5,
  },
  {
    name: "Pistachio Tiramisu",
    price: 180,
    images: ["/public/nhs.png"],
    slug: "pistachio-tiramisu",
    weight: "500ml",
    type: "large",
    description: "Nutty Pistachio flavor Tiramisu with soft texture.",
    reviews: 4.2,
  },

  {
    name: "Lotus Biscoff Tiramisu",
    price: 180,
    images: ["/public/sjhd.png"],
    slug: "lotus-biscoff-tiramisu",
    weight: "500ml",
    type: "large",
    description: "Nutty Pistachio flavor Tiramisu with soft texture.",
    reviews: 4.2,
  },
  {
    name: "Ferrero Rocher Tiramisu",
    price: 180,
    images: ["/public/nhs.png"],
    slug: "ferrero-rocher-tiramisu",
    weight: "500ml",
    type: "large",
    description: "Nutty Pistachio flavor Tiramisu with soft texture.",
    reviews: 4.2,
  },
  {
    name: "Date & Qahwa Tiramisu",
    price: 180,
    images: ["/public/nhs.png"],
    slug: "date-qahwa-tiramisu",
    weight: "500ml",
    type: "large",
    description: "Nutty Pistachio flavor Tiramisu with soft texture.",
    reviews: 4.2,
  },
  {
    name: "Classic Tiramisu",
    price: 90,
    images: ["/public/nhs.png", "/public/sjhd.png"],
    slug: "classic-tiramisu",
    weight: "250ml",
    type: "small",
    description:
      "Delicious classic Tiramisu with rich cream and coffee flavor.",
    reviews: 4.5,
  },
  {
    name: "Pistachio Tiramisu",
    price: 90,
    images: ["/public/nhs.png"],
    slug: "pistachio-tiramisu",
    weight: "250ml",
    type: "small",
    description: "Nutty Pistachio flavor Tiramisu with soft texture.",
    reviews: 4.2,
  },

  {
    name: "Lotus Biscoff Tiramisu",
    price: 90,
    images: ["/public/sjhd.png"],
    slug: "lotus-biscoff-tiramisu",
    weight: "250ml",
    type: "small",
    description: "Nutty Pistachio flavor Tiramisu with soft texture.",
    reviews: 4.2,
  },
  {
    name: "Ferrero Rocher Tiramisu",
    price: 90,
    images: ["/public/nhs.png"],
    slug: "ferrero-rocher-tiramisu",
    weight: "250ml",
    type: "small",
    description: "Nutty Pistachio flavor Tiramisu with soft texture.",
    reviews: 4.2,
  },
  {
    name: "Date & Qahwa Tiramisu",
    price: 90,
    images: ["/public/nhs.png"],
    slug: "date-qahwa-tiramisu",
    weight: "250ml",
    type: "small",
    description: "Nutty Pistachio flavor Tiramisu with soft texture.",
    reviews: 4.2,
  },
];
