export const data = [
  {
    name: "Box of Orginal Jars (250ml x 5)",
    price: 200,
    images: ["/sjhd.png", "/nhs.png", "/nhs.png"],
    slug: "box-of-orginal-jars",
    weight: "250ml X 5",
    type: "box",
    description:
      "A perfect indulgence set featuring five signature flavors: Lotus Biscoff, Ferrero Rocher, Date & Qahwa, Classic, and Pistachio Tiramisu, each rich, layered, and irresistible.",
    reviews: 4.5,
  },
  {
    name: "Box of Pistachio Jars (150ml x 5)",
    price: 180,
    images: ["/sjhd.png", "/nhs.png", "/nhs.png"],
    slug: "box-of-pistachio-jars",
    weight: "150ml X 9",
    type: "box",
    description:
      "A delightful tasting box of nine petite jars with all five tiramisu flavors, crafted for sharing, gifting, or enjoying guilt-free moments of bliss.",
    reviews: 4.2,
  },
  {
    name: "Classic Tiramisu",
    price: 40,
    images: ["/productpage/Classic/DSCF0567.jpg", "/productpage/Classic/DSCF0560.jpg", "/productpage/Classic/DSCF0588.jpg"],
    slug: "classic-tiramisu-150ml",
    weight: "250ml",
    type: "large",
    description:
      "Enjoy the timeless harmony of bold coffee and smooth mascarpone crafted into a truly elegant classic.",
    reviews: 4.5,
  },
  {
    name: "Pistachio Tiramisu",
    price: 40,
    images: ["/productpage/Pistachio/DSCF0830.jpg", "/productpage/Pistachio/DSCF0869.jpg", "/productpage/Pistachio/DSCF0880.jpg"],
    slug: "pistachio-tiramisu-150ml",
    weight: "250ml",
    type: "large",
    description: "Delight in premium pistachios folded into creamy layers for a refined, nutty experience.",
    reviews: 4.2,
  },
  {
    name: "Lotus Biscoff Tiramisu",
    price: 40,
    images: ["/productpage/Lotus Biscoff/DSCF0968.jpg", "/productpage/Lotus Biscoff/DSCF0988.jpg", "/productpage/Lotus Biscoff/DSCF0990.jpg"],
    slug: "lotus-biscoff-tiramisu-150ml",
    weight: "250ml",
    type: "large",
    description:  "Savor the comfort of Lotus with its warm, caramel notes blended into silky, irresistible layers.",
    reviews: 4.2,
  },
  {
    name: "Ferrero Rocher Tiramisu",
    price: 40,
    images: ["/productpage/Ferrero Rocher/DSCF6179.jpg", "/productpage/Ferrero Rocher/DSCF6185.jpg", "/productpage/Ferrero Rocher/DSCF6188.jpg"],
    slug: "ferrero-rocher-tiramisu-150ml",
    weight: "250ml",
    type: "large",
    description: "Indulge in rich hazelnut and velvety chocolate that come together in every decadent spoonful.",
    reviews: 4.2,
  },
  {
    name: "Date & Qahwa Tiramisu",
    price: 40,
    images: ["/productpage/Dates & Kahwah/DSCF1123.jpg", "/productpage/Dates & Kahwah/DSCF1133.jpg", "/productpage/Dates & Kahwah/DSCF1139.jpg"],
    slug: "date-qahwa-tiramisu-150ml",
    weight: "250ml",
    type: "large",
    description: "Experience the magic of premium dates and aromatic Arabic coffee in every luxurious layer.",
    reviews: 4.2,
  },
  {
    name: "Classic Tiramisu",
    price: 25,
    images: ["/productpage/Classic/DSCF0567.jpg", "/productpage/Classic/DSCF0560.jpg", "/productpage/Classic/DSCF0588.jpg"],
    slug: "classic-tiramisu-250ml",
    weight: "150ml",
    type: "small",
    description:
      "Enjoy the timeless harmony of bold coffee and smooth mascarpone crafted into a truly elegant classic.",
    reviews: 4.5,
  },
  {
    name: "Pistachio Tiramisu",
    price: 25,
    images: ["/productpage/Pistachio/DSCF0830.jpg", "/productpage/Pistachio/DSCF0869.jpg", "/productpage/Pistachio/DSCF0880.jpg"],
    slug: "pistachio-tiramisu-250ml",
    weight: "150ml",
    type: "small",
    description: "Delight in premium pistachios folded into creamy layers for a refined, nutty experience.",
    reviews: 4.2,
  },

  {
    name: "Lotus Biscoff Tiramisu",
    price: 25,
    images: ["/productpage/Lotus Biscoff/DSCF0968.jpg", "/productpage/Lotus Biscoff/DSCF0988.jpg", "/productpage/Lotus Biscoff/DSCF0990.jpg"],
    slug: "lotus-biscoff-tiramisu-250ml",
    weight: "150ml",
    type: "small",
    description: "Savor the comfort of Lotus with its warm, caramel notes blended into silky, irresistible layers.",
    reviews: 4.2
  },  
  {
    name: "Ferrero Rocher Tiramisu",
    price: 25,
    images: ["/productpage/Ferrero Rocher/DSCF6179.jpg", "/productpage/Ferrero Rocher/DSCF6185.jpg", "/productpage/Ferrero Rocher/DSCF6188.jpg"],
    slug: "ferrero-rocher-tiramisu-250ml",
    weight: "150ml",
    type: "small",
    description: "Indulge in rich hazelnut and velvety chocolate that come together in every decadent spoonful.",
    reviews: 4.2,
  },
  {
    name: "Date & Qahwa Tiramisu",
    price: 25,
    images: ["/productpage/Dates & Kahwah/DSCF1123.jpg", "/productpage/Dates & Kahwah/DSCF1133.jpg", "/productpage/Dates & Kahwah/DSCF1139.jpg"],
    slug: "date-qahwa-tiramisu-250ml",
    weight: "150ml",
    type: "small",
    description: "Experience the magic of premium dates and aromatic Arabic coffee in every luxurious layer.",
    reviews: 4.2,
  },

  // CASSEROLES (Party Orders)
{
  name: "Classic Tiramisu Casserole (8–10 people)",
  price: 250,
  images: ["/productpage/Casseroles/DSCF1032.jpg", "/productpage/Casseroles/DSCF1048.jpg", "/productpage/Casseroles/DSCF1060.jpg", "/productpage/Casseroles/DSCF1117.jpg"],
  slug: "classic-tiramisu-casserole-8-10",
  weight: "8–10 people",
  type: "casserole",
  description:
    "Your favourite Tiramisu flavour in party size, delivered in a convenient and elegant glass casserole. Pre-order at least 24 hours in advance.",
  reviews: 4.5,
},
{
  name: "Classic Tiramisu Casserole (12–14 people)",
  price: 350,
  images: ["/productpage/Casseroles/DSCF1032.jpg", "/productpage/Casseroles/DSCF1048.jpg", "/productpage/Casseroles/DSCF1060.jpg", "/productpage/Casseroles/DSCF1117.jpg"],
  slug: "classic-tiramisu-casserole-12-14",
  weight: "12–14 people",
  type: "casserole",
  description:
    "Your favourite Tiramisu flavour in party size, delivered in a convenient and elegant glass casserole. Pre-order at least 24 hours in advance.",
  reviews: 4.5,
},
];
